// <auto-generated />
using System;
using HospitalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416162542_ediit")]
    partial class ediit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 4, 20, 17, 41, 57, 0, DateTimeKind.Unspecified),
                            AppointmentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            PatientName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 4, 21, 17, 41, 57, 0, DateTimeKind.Unspecified),
                            AppointmentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientName = "Brown"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2026, 4, 22, 17, 41, 57, 0, DateTimeKind.Unspecified),
                            AppointmentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            PatientName = "Joao"
                        });
                });

            modelBuilder.Entity("HospitalSystem.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Image = "doctor4.jpg",
                            Name = "Dr. Michael Smith",
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 5,
                            Image = "doctor5.jpg",
                            Name = "Dr. Charlie Bob",
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 6,
                            Image = "doctor6.jpg",
                            Name = "Dr. Alice Brown",
                            SpecializationId = 6
                        });
                });

            modelBuilder.Entity("HospitalSystem.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neurology"
                        });
                });

            modelBuilder.Entity("HospitalSystem.Models.Appointment", b =>
                {
                    b.HasOne("HospitalSystem.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalSystem.Models.Doctor", b =>
                {
                    b.HasOne("HospitalSystem.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });
#pragma warning restore 612, 618
        }
    }
}
